name: MSAN

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        cc: [ clang ] # MSan is currently clang only
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bmake pcregrep

    - name: make
      run: bmake -r -j 2 MSAN=1 DEBUG=1 PKGCONF=pkg-config CC=${{ matrix.cc }}

    - name: test
      # I don't want to build SID just for sake of its -l test
      run: bmake -r -j 2 MSAN=1 DEBUG=1 PKGCONF=pkg-config SID='true; echo sid' CC=${{ matrix.cc }} LX=./build/bin/lx test

